CALLS = [
    {
        "id": 522,
        "caller": "+33123456789",
        "callee": "+33752049226",
        "trunk": "TRUNK_SBC_SFR",
        "channel_id": "1781271300.546",
        "call_time_s": 30,
        "duration": 40,
        "hangup_cause": 16,
        "hangup_cause_detail": "Normal Clearing",
        "sip_error_code": None,
        "dtmf": "#12",
        "status": "answered",
        "status_label": "Decroche",
        "error_message": None,
        "scenario_id": 45,
        "scenario_name": "Ivan",
        "scenario_keyword": "bonjour, aide",
        "scenario_category": "SAV",
        "vosk_status": "OK",
        "transcription": "Bonjour, j'ai besoin d'aide pour mon dossier.",
        "keyword_expected": "bonjour, aide",
        "keyword_detected": "bonjour, aide",
        "recording_path": "/srv/asterisk/var/spool/recording/1781271300.546.wav",
        "created_at": "2026-06-12T15:35:43",
        "cdr_disposition": "ANSWERED",
        "keyword_checks": [{"keyword": "bonjour", "status": "OK"}, {"keyword": "aide", "status": "OK"}],
        "voicemail_checks": [],
    },
    {
        "id": 521,
        "caller": "+33111111111",
        "callee": "+33622222222",
        "trunk": "C_SFR_SIRIUS",
        "channel_id": "1781269335.540",
        "call_time_s": 30,
        "duration": 0,
        "hangup_cause": 19,
        "hangup_cause_detail": "No Answer",
        "sip_error_code": None,
        "dtmf": "#41",
        "status": "missed",
        "status_label": "Non decroche",
        "error_message": "Non decroche (CDR)",
        "scenario_id": 44,
        "scenario_name": "NMS",
        "scenario_keyword": "ivan",
        "scenario_category": "GSO",
        "vosk_status": "KO",
        "transcription": "",
        "keyword_expected": "ivan",
        "keyword_detected": None,
        "recording_path": None,
        "created_at": "2026-06-12T15:02:15",
        "cdr_disposition": "NO ANSWER",
        "keyword_checks": [{"keyword": "ivan", "status": "KO"}],
        "voicemail_checks": [],
    },
    {
        "id": 520,
        "caller": "+33123456789",
        "callee": "+33700000000",
        "trunk": "C_SFR_VEGA",
        "channel_id": "1781262300.534",
        "call_time_s": 20,
        "duration": 22,
        "hangup_cause": 16,
        "hangup_cause_detail": "Normal Clearing",
        "sip_error_code": None,
        "dtmf": None,
        "status": "answered",
        "status_label": "Decroche",
        "error_message": None,
        "scenario_id": 43,
        "scenario_name": "Controle messagerie",
        "scenario_keyword": "outils, monitoring",
        "scenario_category": "TEST",
        "vosk_status": "VOICEMAIL",
        "transcription": "Vous etes bien sur la messagerie vocale, veuillez laisser un message.",
        "keyword_expected": "outils, monitoring",
        "keyword_detected": "monitoring",
        "recording_path": "/srv/asterisk/var/spool/recording/1781262300.534.wav",
        "created_at": "2026-06-12T14:56:22",
        "cdr_disposition": "ANSWERED",
        "keyword_checks": [{"keyword": "outils", "status": "KO"}, {"keyword": "monitoring", "status": "OK"}],
        "voicemail_checks": [{"keyword": "messagerie vocale", "status": "OK"}],
    },
    {
        "id": 519,
        "caller": "+33123456789",
        "callee": "+33999999999",
        "trunk": "TRUNK_SBC_SFR",
        "channel_id": None,
        "call_time_s": 15,
        "duration": 0,
        "hangup_cause": 34,
        "hangup_cause_detail": "No Circuit Available",
        "sip_error_code": 503,
        "dtmf": None,
        "status": "trunk_error",
        "status_label": "Erreur trunk",
        "error_message": "SIP 503 - No Circuit Available",
        "scenario_id": 42,
        "scenario_name": "Test trunk",
        "scenario_keyword": "test",
        "scenario_category": "TECH",
        "vosk_status": "KO",
        "transcription": "",
        "keyword_expected": "test",
        "keyword_detected": None,
        "recording_path": None,
        "created_at": "2026-06-12T13:46:06",
        "cdr_disposition": "FAILED",
        "keyword_checks": [{"keyword": "test", "status": "KO"}],
        "voicemail_checks": [],
    },
]

SCENARIOS = [
    {
        "id": 45,
        "name": "Ivan",
        "keyword": "bonjour, aide",
        "category": "SAV",
        "caller": "+33123456789",
        "callee": "+33752049226",
        "trunk": "TRUNK_SBC_SFR",
        "call_time_s": 30,
        "dtmf": "#12",
        "frequency": "weekly",
        "active": 1,
        "created_at": "2026-06-08T10:00:00",
    },
    {
        "id": 43,
        "name": "Controle messagerie",
        "keyword": "outils, monitoring",
        "category": "TEST",
        "caller": "+33123456789",
        "callee": "+33700000000",
        "trunk": "C_SFR_VEGA",
        "call_time_s": 20,
        "dtmf": None,
        "frequency": "daily",
        "active": 1,
        "created_at": "2026-06-08T10:15:00",
    },
]

JOBS = [
    {
        "id": "scenario_45",
        "scenario_id": 45,
        "scenario_name": "Ivan",
        "frequency": "weekly",
        "next_run_time": "2026-06-19T14:30:00+02:00",
        "active": True,
    },
    {
        "id": "scenario_43",
        "scenario_id": 43,
        "scenario_name": "Controle messagerie",
        "frequency": "daily",
        "next_run_time": "2026-06-15T09:00:00+02:00",
        "active": True,
    },
]


def find_call(call_id: int):
    return next((item for item in CALLS if item["id"] == call_id), None)


def find_scenario(scenario_id: int):
    return next((item for item in SCENARIOS if item["id"] == scenario_id), None)


def find_job(job_id: str):
    return next((item for item in JOBS if item["id"] == job_id), None)
